[package]
name = "uacpi-sys"
version = "0.1.0"
authors.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true

[dependencies]

[build-dependencies]
cc = "1.1.34"
